"""Read and write ``harness-plan.yaml`` (ADR-0005).

- Fixed field order instead of ``sort_keys``: byte-stable **and** readable (``kind`` first, ``reason`` last).
- ``evidence`` in flow style (one line), checks as a list of lines — the plan stays reviewable in a PR diff.
- Comment header with provenance and instructions; PyYAML cannot preserve comments, so it is prepended.
- ``decision`` per entry is the only field a human sets; ``merge_decisions`` keeps it across a re-plan via the key
  ``(kind, target, scope)``, follows a renamed unit and names what it drops.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import replace
from pathlib import Path
from typing import Any

import yaml

from sherpa import atomic, schema
from sherpa.apply.state import ADOPTED, State
from sherpa.plan import DECISIONS, Check, Entry, Plan

PLAN_NAME = "harness-plan.yaml"
SCHEMA_PATH = Path(__file__).parent.parent / "schemas" / "harness-plan.schema.json"


class _Flow(dict):
    """A mapping PyYAML writes on one line."""


def _represent_flow(dumper: yaml.SafeDumper, data: _Flow) -> yaml.Node:
    return dumper.represent_mapping("tag:yaml.org,2002:map", data, flow_style=True)


class _Dumper(yaml.SafeDumper):
    pass


_Dumper.add_representer(_Flow, _represent_flow)


def _entry_dict(e: Entry) -> dict[str, Any]:
    d: dict[str, Any] = {
        "kind": e.kind,
        "target": e.target,
        "scope": e.scope,
        "default": e.default,
        "decision": e.decision,
        "evidence": _Flow(e.evidence),
        "checks": [str(c) for c in e.checks],
        "cost": e.cost,
    }
    if e.reason is not None:
        d["reason"] = e.reason
    if e.covered is not None:
        d["covered"] = e.covered
    return d


def to_dict(plan: Plan) -> dict[str, Any]:
    return {
        "sherpa": plan.sherpa,
        "schema_version": plan.schema_version,
        "repo": plan.repo,
        "model": plan.model,
        "thresholds": plan.thresholds,
        "ranking": plan.ranking,
        "notes": list(plan.notes),
        "entries": [_entry_dict(e) for e in plan.entries],
    }


def dumps(plan: Plan) -> str:
    n_yes, n_no = plan.counts()
    head = [
        f"# harness-plan — generated by sherpa {plan.sherpa} from {plan.model['trunk']}@{plan.model['rev'][:10]}",
        f"# {n_yes} proposals, {n_no} reasoned no's. Approve by setting `decision: accept` or `reject` per entry.",
        "# Running `sherpa plan` again keeps decisions you set (key: kind, target, scope).",
        "# Thresholds: sherpa.toml [plan]; rules: docs/concepts/harness-plan.md; principles: ADR-0006, 0011, 0012.",
    ]
    body = yaml.dump(
        to_dict(plan), Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=120, default_flow_style=False
    )
    return "\n".join(head) + "\n" + body


def write(plan: Plan, path: Path) -> None:
    atomic.write_text(path, dumps(plan))  # never a torn plan (ADR-0017)


def loads(text: str) -> dict[str, Any]:
    data = yaml.safe_load(text)
    if not isinstance(data, dict) or "entries" not in data:
        raise ValueError("harness-plan.yaml: not a plan (expected a mapping with 'entries')")
    validate(data)
    return data


def load(path: Path) -> dict[str, Any]:
    return loads(path.read_text(encoding="utf-8"))


def validate(data: dict[str, Any]) -> None:
    """Against the shipped schema with the stdlib validator (ADR-0042) — in production as in the tests, so a typo
    like ``decision: rejcet`` or a foreign ``schema_version`` never reaches ``selected()``."""
    try:
        schema.validate(data, schema.load(SCHEMA_PATH.name))
    except schema.SchemaError as e:
        raise ValueError(f"harness-plan.yaml invalid at {e.path or 'root'}: {e.message}") from None


def decisions_of(data: dict[str, Any]) -> dict[tuple[str, str, str], str]:
    out: dict[tuple[str, str, str], str] = {}
    for e in data.get("entries", []):
        d = e.get("decision")
        if d is None:
            continue
        if d not in DECISIONS:
            raise ValueError(
                f"harness-plan.yaml: decision {d!r} at {e.get('kind')} {e.get('target')} — allowed: {DECISIONS}"
            )
        out[(e["kind"], e["target"], e.get("scope", ""))] = d
    return out


def merge_decisions(plan: Plan, previous: dict[str, Any] | None) -> tuple[Plan, int, list[str]]:
    """Carry decisions over from the previous plan by ``Entry.key``. A decision whose entry is gone follows the
    unit when only its name changed — one decided entry of that kind and scope left the plan and one new entry
    of that kind and scope arrived (F55); anything else is dropped and named, like a vanished cover in
    ``merge_covers`` (F42). Returns (plan, decisions kept — the followed ones included, lines to show)."""
    if not previous:
        return plan, 0, []
    keep = decisions_of(previous)
    known = {(e["kind"], e["target"], e.get("scope", "")) for e in previous.get("entries", [])}
    keys, named = {e.key for e in plan.entries}, {(e.kind, e.target) for e in plan.entries}
    gone = {k: d for k, d in keep.items() if k not in keys}
    left: dict[tuple[str, str], list[tuple[str, str, str]]] = {}  # decided entries whose target left, by kind+scope
    for kind, target, scope in gone:
        if (kind, target) not in named:  # a target still in the plan just moved scope — a different unit, no rename
            left.setdefault((kind, scope), []).append((kind, target, scope))
    arrived = Counter((e.kind, e.scope) for e in plan.entries if e.key not in known)
    entries, n, lines, followed = [], 0, [], set()
    for e in plan.entries:
        d = keep.get(e.key)
        at = (e.kind, e.scope)
        if d is None and e.key not in known and arrived[at] == 1 and len(left.get(at, ())) == 1:
            (old,) = left[at]  # one left, one arrived, same kind and path: the unit was renamed
            d, followed = keep[old], followed | {old}
            lines.append(f"{e.address} [{d}] — followed from {_address(old)} (same path, renamed)")
        if d is not None:
            n += 1
            e = replace(e, decision=d)
        entries.append(e)
    dropped = [f"{_address(k)} [{d}] is no longer in the plan — dropped" for k, d in gone.items() if k not in followed]
    return replace(plan, entries=entries), n, dropped + lines


def _address(key: tuple[str, str, str]) -> str:
    return ":".join(key)


def decide(plan: Plan, accept: list[str], reject: list[str]) -> tuple[Plan, int]:
    """``sherpa plan --accept agent:pay --reject owner-doc:web``: decisions by address, for scripts and CI.

    An address is ``kind:target`` or ``kind:target:scope`` (``Entry.address``); without the scope it must match
    exactly one entry. Unknown or ambiguous addresses are errors that list what exists. Returns the plan and the
    number of decisions set; the YAML is still the record — a flag writes the same ``decision:`` a hand would."""
    wanted: list[tuple[str, str]] = [(a, "accept") for a in accept] + [(r, "reject") for r in reject]
    if not wanted:
        return plan, 0
    by_address = {e.address: e for e in plan.entries}
    resolved: dict[str, str] = {}
    for addr, decision in wanted:
        if addr in by_address:
            hits = [addr]
        else:
            hits = [a for a in by_address if a.startswith(addr + ":")]
        if not hits:
            kind = addr.split(":")[0]
            same = [a for a in by_address if a.split(":")[0] == kind]
            if ":" not in addr or not same:
                kinds = ", ".join(sorted({a.split(":")[0] for a in by_address}))
                raise ValueError(f"--{decision} {addr}: expected <kind>:<unit> — kinds in this plan: {kinds}")
            shown = ", ".join(same[:5]) + (f" (+{len(same) - 5} more)" if len(same) > 5 else "")
            raise ValueError(f"--{decision} {addr}: no such entry — entries of that kind: {shown}")
        if len(hits) > 1:
            raise ValueError(f"--{decision} {addr}: ambiguous — {', '.join(hits)}; give the scope")
        if resolved.get(hits[0], decision) != decision:
            raise ValueError(f"{hits[0]}: both --accept and --reject given")
        resolved[hits[0]] = decision
    entries = [replace(e, decision=resolved[e.address]) if e.address in resolved else e for e in plan.entries]
    return Plan(
        plan.repo, plan.model, plan.thresholds, plan.ranking, entries, plan.sherpa, plan.schema_version, plan.notes
    ), len(resolved)


def plan_from_dict(d: dict[str, Any]) -> Plan:
    """The stored plan back as a ``Plan`` — ``sherpa apply`` and ``status`` work on what the human approved."""
    validate(d)
    return Plan(
        repo=d["repo"],
        model=dict(d.get("model", {})),
        thresholds=dict(d.get("thresholds", {})),
        ranking=dict(d.get("ranking", {})),
        entries=[entry_from_dict(e) for e in d.get("entries", [])],
        sherpa=d.get("sherpa", ""),
        schema_version=int(d.get("schema_version", 1)),
        notes=list(d.get("notes", [])),
    )


def entry_from_dict(d: dict[str, Any]) -> Entry:
    """For tests and later commands (``apply`` reads the plan back)."""
    checks = tuple(Check(*_split_check(c)) for c in d.get("checks", []))
    return Entry(
        d["kind"],
        d["target"],
        d.get("scope", ""),
        d["default"],
        dict(d.get("evidence", {})),
        checks,
        d.get("cost", ""),
        d.get("reason"),
        d.get("decision"),
        d.get("covered"),
    )


def covers_of(data: dict[str, Any]) -> dict[tuple[str, str, str], str]:
    return {
        (e["kind"], e["target"], e.get("scope", "")): e["covered"]
        for e in data.get("entries", [])
        if isinstance(e.get("covered"), str) and e["covered"]
    }


def merge_covers(plan: Plan, previous: dict[str, Any] | None, repo: Path) -> tuple[Plan, int, list[str]]:
    """Carry ``covered:`` over from the previous plan — the human's word on which existing file fills an entry
    (ADR-0046), kept like a decision. A path that no longer exists is dropped and named. Returns (plan, kept,
    dropped lines)."""
    if not previous:
        return plan, 0, []
    keep = covers_of(previous)
    entries, n, dropped = [], 0, []
    for e in plan.entries:
        path = keep.get(e.key)
        if path is None:
            entries.append(e)
        elif (repo / path).is_file():
            n += 1
            entries.append(replace(e, covered=path))
        else:
            dropped.append(f"{e.address} was covered by {path}, which no longer exists — dropped")
            entries.append(e)
    return replace(plan, entries=entries), n, dropped


def mark_covered(
    plan: Plan, state: State, repo: Path | None = None, by_path: dict[str, str] | None = None
) -> tuple[Plan, int]:
    """An adopted file linked to an entry covers it (ADR-0007): the plan shows the file, ``apply`` renders nothing
    for the entry unless a human accepts it explicitly. One precedence, in one place: the plan's own word (a
    hand-written ``covered:``, ADR-0046) · the unit's own ``AGENTS.md`` (``by_path``, entry address → path,
    ADR-0049; written like a hand-written one, so ``merge_covers`` keeps it) · the state's link, for entries
    without a decision. A record whose file is gone covers nothing (``status`` names it, ``adopt`` drops it).
    Returns the plan and the number of covered entries."""
    by_key: dict[str, str] = {}
    for path, rec in sorted(state.files.items()):
        if rec.origin == ADOPTED and rec.entry and (repo is None or (repo / path).is_file()):
            by_key.setdefault(rec.entry, path)
    entries, n = [], 0
    for e in plan.entries:
        covered = e.covered or (by_path or {}).get(e.address)
        if covered is None and e.decision is None:  # a decision stands alone
            covered = by_key.get(e.address)
        n += covered is not None
        entries.append(replace(e, covered=covered))
    return replace(plan, entries=entries), n


def _split_check(text: str) -> tuple[str, bool, str]:
    ok = text.endswith(" ✓")
    body = text[:-2]
    if body.endswith(")") and " (" in body:
        label, need = body.rsplit(" (", 1)
        return label, ok, need[:-1]
    return body, ok, ""
