"""Read and write ``harness-plan.yaml`` (ADR-0005).

- Fixed field order instead of ``sort_keys``: byte-stable **and** readable (``kind`` first, ``reason`` last).
- ``evidence`` in flow style (one line), checks as a list of lines — the plan stays reviewable in a PR diff.
- Comment header with provenance and instructions; PyYAML cannot preserve comments, so it is prepended.
- ``decision`` per entry is the only field a human sets; ``merge_decisions`` keeps it across a re-plan via the key
  ``(kind, target, scope)``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

from sherpa.plan import DECISIONS, Check, Entry, Plan

PLAN_NAME = "harness-plan.yaml"
SCHEMA_PATH = Path(__file__).parent.parent / "schemas" / "harness-plan.schema.json"


class _Flow(dict):
    """A mapping PyYAML writes on one line."""


def _represent_flow(dumper: yaml.SafeDumper, data: _Flow) -> yaml.Node:
    return dumper.represent_mapping("tag:yaml.org,2002:map", data, flow_style=True)


class _Dumper(yaml.SafeDumper):
    pass


_Dumper.add_representer(_Flow, _represent_flow)


def _entry_dict(e: Entry) -> dict[str, Any]:
    d: dict[str, Any] = {
        "kind": e.kind,
        "target": e.target,
        "scope": e.scope,
        "default": e.default,
        "decision": e.decision,
        "evidence": _Flow(e.evidence),
        "checks": [str(c) for c in e.checks],
        "cost": e.cost,
    }
    if e.reason is not None:
        d["reason"] = e.reason
    return d


def to_dict(plan: Plan) -> dict[str, Any]:
    return {
        "sherpa": plan.sherpa,
        "schema_version": plan.schema_version,
        "repo": plan.repo,
        "model": plan.model,
        "thresholds": plan.thresholds,
        "ranking": plan.ranking,
        "notes": list(plan.notes),
        "entries": [_entry_dict(e) for e in plan.entries],
    }


def dumps(plan: Plan) -> str:
    n_yes, n_no = plan.counts()
    head = [
        f"# harness-plan — generated by sherpa {plan.sherpa} from {plan.model['trunk']}@{plan.model['rev'][:10]}",
        f"# {n_yes} proposals, {n_no} reasoned no's. Approve by setting `decision: accept` or `reject` per entry.",
        "# Running `sherpa plan` again keeps decisions you set (key: kind, target, scope).",
        "# Thresholds: sherpa.toml [plan]; rules: docs/harness-plan.md; principles: ADR-0006, ADR-0011, ADR-0012.",
    ]
    body = yaml.dump(
        to_dict(plan), Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=120, default_flow_style=False
    )
    return "\n".join(head) + "\n" + body


def write(plan: Plan, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(dumps(plan), encoding="utf-8", newline="\n")


def loads(text: str) -> dict[str, Any]:
    data = yaml.safe_load(text)
    if not isinstance(data, dict) or "entries" not in data:
        raise ValueError("harness-plan.yaml: not a plan (expected a mapping with 'entries')")
    validate(data)
    return data


def load(path: Path) -> dict[str, Any]:
    return loads(path.read_text(encoding="utf-8"))


def validate(data: dict[str, Any]) -> None:
    """Validate against the JSON schema when ``jsonschema`` is installed (dev extra); otherwise no-op."""
    try:
        import jsonschema  # type: ignore
    except ImportError:  # pragma: no cover
        return
    try:
        jsonschema.validate(data, json.loads(SCHEMA_PATH.read_text(encoding="utf-8")))
    except jsonschema.ValidationError as e:
        where = "/".join(str(x) for x in e.absolute_path)
        raise ValueError(f"harness-plan.yaml invalid at {where or 'root'}: {e.message}") from None


def decisions_of(data: dict[str, Any]) -> dict[tuple[str, str, str], str]:
    out: dict[tuple[str, str, str], str] = {}
    for e in data.get("entries", []):
        d = e.get("decision")
        if d is None:
            continue
        if d not in DECISIONS:
            raise ValueError(
                f"harness-plan.yaml: decision {d!r} at {e.get('kind')} {e.get('target')} — allowed: {DECISIONS}"
            )
        out[(e["kind"], e["target"], e.get("scope", ""))] = d
    return out


def merge_decisions(plan: Plan, previous: dict[str, Any] | None) -> tuple[Plan, int]:
    """Carry decisions over from the previous plan. Returns (plan, number of decisions kept)."""
    if not previous:
        return plan, 0
    keep = decisions_of(previous)
    entries, n = [], 0
    for e in plan.entries:
        d = keep.get(e.key)
        if d is not None:
            n += 1
            e = Entry(e.kind, e.target, e.scope, e.default, e.evidence, e.checks, e.cost, e.reason, d)
        entries.append(e)
    return Plan(
        plan.repo, plan.model, plan.thresholds, plan.ranking, entries, plan.sherpa, plan.schema_version, plan.notes
    ), n


def entry_from_dict(d: dict[str, Any]) -> Entry:
    """For tests and later commands (``apply`` reads the plan back)."""
    checks = tuple(Check(*_split_check(c)) for c in d.get("checks", []))
    return Entry(
        d["kind"],
        d["target"],
        d.get("scope", ""),
        d["default"],
        dict(d.get("evidence", {})),
        checks,
        d.get("cost", ""),
        d.get("reason"),
        d.get("decision"),
    )


def _split_check(text: str) -> tuple[str, bool, str]:
    ok = text.endswith(" ✓")
    body = text[:-2]
    if body.endswith(")") and " (" in body:
        label, need = body.rsplit(" (", 1)
        return label, ok, need[:-1]
    return body, ok, ""
